import os
import requests
from dotenv import load_dotenv

load_dotenv()

BITBUCKET_USERNAME = os.getenv("BITBUCKET_USERNAME")
BITBUCKET_APP_PASSWORD = os.getenv("BITBUCKET_APP_PASSWORD")
WORKSPACE = os.getenv("BITBUCKET_WORKSPACE_ID")
REPO_SLUG = os.getenv("BITBUCKET_REPO_SLUG")

auth = (BITBUCKET_USERNAME, BITBUCKET_APP_PASSWORD)

def create_branch(branch_name, source="master"):
    url = f"https://api.bitbucket.org/2.0/repositories/{WORKSPACE}/{REPO_SLUG}/refs/branches"
    data = {
        "name": branch_name,
        "target": {"hash": source}
    }
    res = requests.post(url, json=data, auth=auth)
    return res.ok

def commit_code(branch_name, filename, code):
    url = f"https://api.bitbucket.org/2.0/repositories/{WORKSPACE}/{REPO_SLUG}/src"
    data = {
        "branch": branch_name,
        "message": f"Auto-generated code for {filename}"
    }
    files = {
        filename: code
    }
    res = requests.post(url, data=data, files=files, auth=auth)
    return res.ok

def create_pull_request(branch_name, title):
    url = f"https://api.bitbucket.org/2.0/repositories/{WORKSPACE}/{REPO_SLUG}/pullrequests"
    data = {
        "title": title,
        "source": {"branch": {"name": branch_name}},
        "destination": {"branch": {"name": "master"}},
        "description": "This PR was auto-generated by an AI workflow."
    }
    res = requests.post(url, json=data, auth=auth)
    print("Bitbucket PR creation response:", res.json())
    return res.json()
